language: bash
sudo: true

services:
  - docker

before_cache:
  # Save tagged docker images
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker-compose pull

cache:
  bundler: true
  directories:
    - $HOME/docker
    - vendor

jobs:  
  include:
    - stage: Tests
      name: Lint tests               
      script: docker-compose run api composer test-lint
    
    - stage: Tests
      name: Unit tests 
      script: docker-compose run api composer test-unit

    - stage: Tests
      name: Integration tests 
      script: docker-compose run api composer test-e2e

    - stage: Deploy
      name: Deploy to heroku production
      deploy: &heroku
        on: master
        provider: heroku
        app: asterismo
        api_key: $HEROKU_AUTH_TOKEN
    
    - stage: Deploy
      name: Deploy to heroku staging
      deploy: &heroku
        on: develop
        provider: heroku
        app: asterismo-develop
        api_key: $HEROKU_AUTH_TOKEN
