language: bash
sudo: true

services:
  - docker

before_cache:
  # Save tagged docker images
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker-compose pull

cache:
  bundler: true
  directories:
    - $HOME/docker
    - vendor

jobs:  
  include:
    - stage: Build
      name: Build docker image  
      script: docker-compose build

    - stage: Tests
      name: Lint tests
      script: docker-compose run api composer test-lint
    
    - stage: Tests
      name: Unit tests
      script: docker-compose run api composer test-unit

    - stage: Tests
      name: e2e tests
      script: docker-compose run api composer test-e2e
    
    - stage: Deploy
      name: Deploy to heroku staging
      deploy: &heroku
        on: develop
        skip_cleanup: true
        provider: heroku
        app: asterismo-staging
        api_key: $HEROKU_AUTH_TOKEN

    - stage: Deploy
      name: Deploy to heroku production
      deploy: &heroku
        on: master
        skip_cleanup: true
        provider: heroku
        app: asterismo
        api_key: $HEROKU_AUTH_TOKEN

    - stage: Deploy
      name: Deploy to github repository
      deploy: &script
        on: master, develop
        skip_cleanup: true
        provider: script
        script: 
          - cd $HOME
          - git config --global user.email "bot@gerardo-junior.com"
          - git config --global user.name "Bot of gerardo"
          - git clone --recurse-submodules -b $TRAVIS_BRANCH https://github.com/gerardo-junior/asterismo
          - cd asterismo
          - git submodule update --remote api
          - git add api
          - git commit -m "TRAVIS api \#${TRAVIS_BUILD_NUMBER} - Updating submodule api"
          - git push --force --repo https://${GITHUB_BOT_AUTH_TOKEN}@github.com/gerardo-junior/asterismo
          - cd ../ && rm -rf asterismo
