language: bash
sudo: true

services:
  - docker

before_cache:
  # Save tagged docker images
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker-compose pull

cache:
  bundler: true
  directories:
    - $HOME/docker
    - vendor

jobs:  
  include:
    - stage: Tests
      name: Lint tests               
      script: echo "run lint tests...'
    
    - stage: Tests
      name: Unit tests 
      script: echo "run unit tests...'

    - stage: Tests
      name: Integration tests 
      script: echo "run integration tests...'

    - stage: Deploy
      name: Deploy to heroku
      deploy: &heroku
        provider: heroku
        app: asterismo.api
        api_key: $HEROKU_AUTH_TOKEN