version: "3.4"
services:

  api: 
    image: gerardojunior/symfony:stable
    build: .docker
    volumes:
      - type: bind
        source: ./
        target: /usr/share/src
    ports:
      - 1234:80
      # - 9000:9000 # xdebug port
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3.11
    restart: on-failure
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=asterismo
      - MYSQL_USER=asterismo
      - MYSQL_PASSWORD=asterismo
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        volume:
          nocopy: true

volumes:
  dbdata:
    name: "asterismo-dbdata"
